import { test } from 'node:test'
import { deepEqual } from 'node:assert'

import { dittoSplitPaths, BrokerRowModel, t } from './app-store.js'


test('dittoSplitPaths', () => {
	const input = [
		'/api/user',
		'/api/user/avatar',
		'/api/user/friends',
		'/api/vid',
		'/api/video/id',
		'/api/video/stats',
		'/v2/foo',
		'/v2/foo/bar'
	]
	deepEqual(dittoSplitPaths(input), [
		['', '/api/user'],
		['/api/user/', 'avatar'],
		['/api/user/', 'friends'],
		['/api/', 'vid'],
		['/api/', 'video/id'],
		['/api/video/', 'stats'],
		['', '/v2/foo'],
		['/v2/foo/', 'bar']
	])
})


test('BrokerRowModel', () => {
	test('has Auto500 when is autogenerated 500', () => {
		const broker = {
			auto500: true,
			file: 'api/user.GET.200.json',
			mocks: ['api/user.GET.200.json']
		}
		const row = new BrokerRowModel(broker, false)
		const opts = row.opts.map(([, n, selected]) => [n, selected])
		deepEqual(opts, [
			['200 json', false],
			[t`Auto500`, true],
		])
	})

	test('filename has extension except when empty or unknown', () => {
		const broker = {
			file: `api/user0.GET.200.empty`,
			mocks: [
				`api/user0.GET.200.empty`,
				`api/user1.GET.200.unknown`,
				`api/user2.GET.200.json`,
				`api/user3(another json).GET.200.json`,
			]
		}
		const row = new BrokerRowModel(broker, false)
		const opts = row.opts.map(([, n, selected]) => [n, selected])
		deepEqual(opts, [
			['200', true],
			['200', false],
			['200 json', false],
			['200 json (another json)', false]
		])
		// TODO Think about, in cases like this, the only option the user has
		//  for discerning empty and unknown is on the Previewer Title
	})

	test('appends "Proxied" label iff current is proxied', () => {
		const broker = {
			file: 'api/foo',
			proxied: true,
			mocks: [`api/foo.GET.200.json`]
		}
		const row = new BrokerRowModel(broker, true)
		deepEqual(row.opts.map(([, n, selected]) => [n, selected]), [
			['200 json', false],
			[t`Proxied`, true]
		])
	})
})

