name: Pixaton
on:
  workflow_dispatch:
  push:
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
        env:
          TMPDIR: ${{ runner.temp }}

      - name: Install dependencies
        run: npm ci

      - name: Run Pixaton Tests
        run: script -q -e -c 'npm run pixaton'

      - name: Upload Pixaton Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: pixaton-artifacts
          path: pixaton-tests/ubuntu/*.png
