name: Test
on: [push]
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
        env:
          TMPDIR: ${{ runner.temp }}
      - run: node --test src/**.test.js
