name: Test
on: [ push, pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:24-slim
    steps:
      - uses: actions/checkout@v5
      - run: npm run coverage

      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
